### PR TITLE
Mj/more card styles

### PR DESCRIPTION
**Pull request by mjordancodes**
Summary of changes
- adds new card style: NEON MODE!
- updates styling on rainbow mode to include rainbow gradient text
- updates image styling on dark mode 

Screen Shot 2022-10-30 at 1 34 07 PM
Screen Shot 2022-10-30 at 1 34 13 PM
Screen Shot 2022-10-30 at 1 34 20 PM

### CODE REVIEW

**Comment by jischr** [comment]
@mjordancodes getting a compile error when this tries to deploy.

**Comment by domsbytes** [comment]
loving the new designs :) @mjordancodes

**Comment by domsbytes** [comment]
compile error: 1:04:52 PM: https://github.com/browserslist/browserslist#browsers-data-updating
1:04:52 PM: 
1:04:52 PM: Treating warnings as errors because process.env.CI = true.
1:04:52 PM: Most CI servers set it automatically.
1:04:52 PM: 
1:04:52 PM: Failed to compile.
1:04:52 PM: 
1:04:52 PM: [eslint]
1:04:52 PM: src/cards/mjordanCard/jordanCard.jsx
1:04:52 PM:   Line 62:27:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
1:04:53 PM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
1:04:53 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mjordancodes** [comment]
Should be fixed now

**Review by jischr — APPROVED** [review]

**Pull request merged**
