### PR TITLE
Issue#94/add dark mode jenn diaz

### PR DESCRIPTION
**Pull request by jenndiaz**
# Summary of changes
Adds a dark mode to card for Jenn Diaz 
Small ghost animation appears when switching to dark mode 

Bonus - adjusted css for Chay's card as it was globally applying to all buttons 

# How to test (for features) / reproduce (for bugs)
Clicking on Dark Mode button should invert colors and a small ghost should fade in and then fade back out 
There should be no visible changes to chay's button

# Screenshots
screenshot
screenshot

# Changes include
- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Documentation (explains but does not affect functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Notes

### CODE REVIEW

**Comment by jenndiaz** [comment]
Seeing that the build failed, looking into it.

**Comment by jischr** [comment]
I LOVE THIS! 
only one thought... could you switch the text to say "Light Mode" when you're in dark mode and want to switch back?

**Comment by jischr** [comment]
Thanks for the updates to chay's card!!!!

**Comment by jenndiaz** [comment]
> I LOVE THIS! only one thought... could you switch the text to say "Light Mode" when you're in dark mode and want to switch back?

Thanks and I agree was over thinking this button, updated to me more specific!

**Review by jischr — APPROVED** [review]
This is too amazing! 👏

**Pull request merged**
