### PR TITLE
Add logo concepts

### PR DESCRIPTION
**Pull request by Kitkatnik**
# Summary of changes

- Added two logos for Scrollodex light background

# Related Issue

- #10 

# Screenshots

Scrollodex_V1_Light
Scrollodex_V2_Light

# Notes

- I can add more concepts and dark background versions soon (it's testing week at my bootcamp 😅)

### CODE REVIEW

**Comment by jischr** [comment]
I LOVE these!!! Such a great job. To match colors exactly:
The Women Who Code Teal is 
Women Who Code Teal
#007D7F
R 0 G 125 B 127
C 85 M 19 Y 38 K 16

**Comment by Kitkatnik** [comment]
> I LOVE these!!! Such a great job. To match colors exactly: The Women Who Code Teal is #007D7F R 0 G 125 B 127 C 85 M 19 Y 38 K 16

yessss thank you for this!! I'll work on that + add another concept that I liked but couldn't get done + dark mode logos :D

**Comment by jischr** [comment]
Screen Shot 2022-10-24 at 7 32 22 PM
 Other WWCode colors! Yellow is preferred for dark mode if it looks ok!

**Comment by domsbytes** [comment]
these look so COOL! @Kitkatnik ! Love the little O that looks like a rolodex lol genius

**Comment by Kitkatnik** [comment]
> Screen Shot 2022-10-24 at 7 32 22 PM Other WWCode colors! Yellow is preferred for dark mode if it looks ok!

Ahhh sorry I just saw this!! I just pushed a few logos with white but I can try yellow as well if you want?

# Logo Preview

## V1

Scrollodex_Logo_V1_Dark
Scrollodex_Logo_V1_Light

## V2 

### A

Scrollodex_Logo_V2_Dark
Scrollodex_Logo_V2_Light

### B

Scrollodex_Logo_V2b_Dark
Scrollodex_Logo_V2b_Light

## V3

Scrollodex_Logo_V3_Dark
Scrollodex_Logo_V3_Light

**Comment by Kitkatnik** [comment]
And I got ANOTHER idea for a logo 😅 if it looks good I'll upload it too lol

**Comment by Kitkatnik** [comment]
Added all logos with yellow :)

And added in another concept. This one didn't look good with yellow though

# V1

Scrollodex_Logo_V1_Yellow1
Scrollodex_Logo_V1_Yellow2

# V2

## A

Scrollodex_Logo_V2_Yellow1
Scrollodex_Logo_V2_Yellow2

## B

Scrollodex_Logo_V2b_Yellow1
Scrollodex_Logo_V2b_Yellow2

# V3

Scrollodex_Logo_V3_Yellow1
Scrollodex_Logo_V3_Yellow2

# V4 (new)

Scrollodex_Logo_V4_Dark
Scrollodex_Logo_V4_Light

**Comment by jischr** [comment]
@Kitkatnik love this! Let's merge them all in if you're ok with that?

**Comment by Kitkatnik** [comment]
> @Kitkatnik love this! Let's merge them all in if you're ok with that?

Of course! :)

**Review by jischr — APPROVED** [review]

**Pull request merged**
