### PR TITLE
Issue#12/create footer

### PR DESCRIPTION
**Pull request by jenndiaz**
# Summary of changes
Adds a responsive footer component!

# Related Issue
#12 

# How to test (for features) / reproduce (for bugs)
footer should be visible 
On screens < 700px footer should adults from 3 cols to 1 col.

# Screenshots
## Desktop
screenshot
## Mobile
Screen Shot 2022-10-20 at 4 45 57 PM

# Changes include
- [x] New feature (non-breaking change that adds functionality)

# Notes
Could use further designing if someone is interested!

### CODE REVIEW

**Comment by jischr** [comment]
@jenndiaz styling looks kind of weird as i shrink the size of my browser. can you take a look at that?

**Comment by jenndiaz** [comment]
> @jenndiaz styling looks kind of weird as i shrink the size of my browser. can you take a look at that?

@jischr hmm I am not seeing any issues and I checked on Safari and Chrome, what browser were using? and is it at a specific breakpoint?

**Comment by jischr** [comment]
@jenndiaz Ah so I think it was that I was expecting the footer breakpoint to be the same as the cards. Up to you for what you feel like looks best.

Screen Shot 2022-10-22 at 12 31 40 PM

**Comment by jenndiaz** [comment]
@jischr oh I see what you mean! Was so focused on the footer I wasn't paying attention to the cards. This is why we have designers 😂, Updated the footer breakpoints to match!

**Comment by domsbytes** [comment]
Loving this nice and simpe header @jenndiaz , I think we can create a new issue to update the logo later 👍 , merging her in !

**Pull request merged**
